service: news-crawler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.hello
